apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  namespace: default
spec:
  type: LoadBalancer #For outside to see
  ports:
  - port: 80
    targetPort: 2368
    nodePort: 32000
    protocol: TCP
  selector:
    app: ghost-blog
